### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by louislang** [serialfuzzer/AngulerJS#1]
Hello, I'm a co-founder at [Phylum](https://phylum.io). We actively monitor open-source package registries for signs of software supply chain attacks. Our system recently alerted us to a rather large campaign that appears to be typosquatting `react` and `angular` packages in npm. The `package.json` references this GitHug repository.

Curious what the intent of this campaign is, and whether or not it's tied to this repository at all?

**Comment by serialfuzzer** [comment]
Hi @louislang,

Thank you for your concern.

This is not a malware, technically this would only send some basic information about the host to me. This was created for two reasons:
1. Find out if any of the bug bounty programs I'm participating in gets affected by one of the packages so that I could be the first one to notify them and protect their infrastructure.
2. Find out how many people make mistakes such as this. The packages won't do anything malicious or collect any sensitive information, right now the project collects following information:
i. IP Addresses (including Public IP Address for host identification)
ii. Username
iii. Hostname

**Comment by louislang** [comment]
As someone who has participated in bug bounties in the past, I'll say that these shotgun style approaches are unlikely to yield results. As a user of open source package registries, I'd typically prefer to _not install_ packages that collect information about my machine in the event I do typo a package name by mistake. In short, this is probably ill advised (and I'm asuming benevolent intent here, and hoping this wasn't really a vector for more malicious publications down the line).

I'm not the npm police, but I'd point out that this sort of activity appears to be in violation of their [acceptable use policy](https://docs.npmjs.com/policies/open-source-terms#acceptable-use) for package publications. Specifically section (3):

> Content containing malicious computer code, such as computer viruses, computer worms, rootkits, back doors, or spyware. This includes content submitted for research purposes. Tools designed and documented explicitly to assist in security research are acceptable, but exploits and malware that use the npm registry as a deployment or delivery vector are not.

Not to mention it muddies the waters for individuals tasked with cleaning up packages at npm, resulting in longer takedown times for other malicious publications.

**Comment by serialfuzzer** [comment]
Sure, I've started a routine to remove all the data collector scripts. Since NPM has a rate limit and there are a lot of packages, it's going to take some time.

**Comment by serialfuzzer** [comment]
@louislang,
Closing this as all data collector scripts have been removed from NPM. All of them are `v8.7.6`, I hope NPM replaces them with **Security warning.**, I'd like to add a suggestion here for anyone reading this and interested to prevent dependency confusion on their package: **You can use https://github.com/serialfuzzer/blunderbus to create most possible typos for your package and publish them before a malicious actor does**
